M48
; DRILL file {KiCad (6.0.0-0)} date Tuesday, March 28, 2023 at 01:07:50 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-28T13:07:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X24.28Y-31.452
X29.28Y-31.452
T2
X40.513Y-34.29
T3
X28.595Y-40.005
X28.595Y-51.435
T0
M30
